services:
  web:
    image: nginx:1.27.1
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal

  php-fpm:
    build:
      context: .
      dockerfile: php.dev.Dockerfile
    volumes:
      - ./src:/var/www/src
      - ./public:/var/www/html 
      - ./.env:/var/www/.env
      - ./vendor:/var/www/vendor
    networks:
      - internal
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
  postgresql:
    image: postgres:16.4
    environment:
      POSTGRES_DB: db_looper
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    networks:
      - internal

  pgadmin4:
    image: elestio/pgadmin:REL-8_11
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8081:8080"
    networks:
      - internal

  mongodb:
    image: mongodb/mongodb-community-server:7.0.5-ubuntu2204
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./.mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
