services:
  web:
    image: nginx:1.27.1
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal

  php-fpm:
    build:
      context: .
      dockerfile: php.prod.Dockerfile
    volumes:
      - ./src:/var/www/src
      - ./public:/var/www/html 
      - ./.env:/var/www/.env
      - ./vendor:/var/www/vendor
    networks:
      - internal
  postgresql:
    image: postgres:16.4
    environment:
      POSTGRES_DB: db_looper
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    networks:
      - internal

  mongodb:
    image: mongodb/mongodb-community-server:7.0.5-ubuntu2204
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./.mongo_data:/data/db
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
